### PR TITLE
Cpp Processing to Install

### PR DESCRIPTION
**Pull request by bnhassin**
Add command Yaml steps for c++language

### CODE REVIEW

**Comment by BanzaiMan** [comment]
What is this PR supposed to achieve?

**Comment by bnhassin** [comment]
Why i have some build installed? https://app.netlify.com/sites/keen-nobel-eb6066/overview

**Comment by bnhassin** [comment]
Duplicate of #2426

**Comment by joshk** [comment]
I think this might be spam?

**Comment by bnhassin** [comment]
@joshk submitted form draft PR

**Comment by joshk** [comment]
Closing as I don't know what this is trying to achieve

**Pull request closed without merging**
