### PR TITLE
fix broken links

### PR DESCRIPTION
**Pull request by robertfausk**
by adding missing dir 'user'.

Maybe some doc pages was moved in user dir without adopting internal links.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
I believe the current links are correct. See https://docs.travis-ci.com/user/sauce-connect/ and https://travis-ci.org/travis-ci/docs-travis-ci-com/builds/256928903#L555-L561

Where do you see the errors?

**Comment by robertfausk** [comment]
It seems that it depends on the uri the user is coming from.
Wether it has a trailing slash or not.

There is currently following behavior:
* https://docs.travis-ci.com/user/sauce-connect#stq=&stp=0 shows broken links
* also https://docs.travis-ci.com/user/sauce-connect shows broken links
* https://docs.travis-ci.com/user/sauce-connect/ shows correct links

I think we need another PR ;)

image

**Comment by BanzaiMan** [comment]
Thanks for the info. This should be fixed by https://github.com/travis-ci/docs-travis-ci-com/commit/7f0030bf85b59c13066f8254767676dd392e9b27.

One interesting thing to note is that https://docs.travis-ci.com/user/sauce-connect _should_ be redirected to https://docs.travis-ci.com/user/sauce-connect/, (at least, that is how the app behaves locally) but isn't.

**Comment by BanzaiMan** [comment]
Hmm. The issue seems to persist.

@robertfausk Do you mind opening a separate ticket? Thanks.

**Pull request closed without merging**
