### PR TITLE
Partner queue solution doc updates

### PR DESCRIPTION
**Pull request by michal-at-travisci**
Partner queue solution doc updates

### CODE REVIEW

**Review by nrios14 — DISMISSED** [review]

**Review by Montana — APPROVED** [review]
Billing review changes look good, markdown is good.

**Review by stan-travis — DISMISSED** [review]
Looks Good To Me

**Comment by michal-at-travisci** [comment]
Thanks for reviewing!

**Comment by Montana** [comment]
Perfect!

**Pull request merged**
