### PR TITLE
optimize png images using zopflipng

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Re-compress png images losslessly using Google's zopflipng, 51 png images optimized as below:

```
 api/images/logo.png                             | Bin 44115 -> 28712 bytes
 images/anika-hs.png                             | Bin 310040 -> 297669 bytes
 images/apps/build-checker-app.png               | Bin 4853 -> 3374 bytes
 images/apps/catlight-tray.png                   | Bin 7260 -> 6070 bytes
 images/apps/ci-status.png                       | Bin 167525 -> 98316 bytes
 images/apps/git.png                             | Bin 14278 -> 11891 bytes
 images/apps/tron.png                            | Bin 12398 -> 11508 bytes
 images/atom_feed_add.png                        | Bin 54164 -> 49573 bytes
 images/atom_feed_view.png                       | Bin 236542 -> 144269 bytes
 images/bluebox.png                              | Bin 3831 -> 1838 bytes
 images/blueboxteam-small.png                    | Bin 212527 -> 185063 bytes
 images/blueboxteam.png                          | Bin 1087992 -> 916297 bytes
 images/caches-item.png                          | Bin 17145 -> 9343 bytes
 images/cli-cache.png                            | Bin 28393 -> 17536 bytes
 images/cloudcontrol.png                         | Bin 5405 -> 4589 bytes
 images/coveralls-button.png                     | Bin 2174 -> 1556 bytes
 images/cron-adding.png                          | Bin 12958 -> 6569 bytes
 images/cron-created.png                         | Bin 30596 -> 12453 bytes
 images/cron-deleting.png                        | Bin 1614014 -> 13561 bytes
 images/cron-section.png                         | Bin 59861 -> 29378 bytes
 images/deploy.png                               | Bin 18443 -> 12128 bytes
 images/dscape.png                               | Bin 213579 -> 139814 bytes
 images/encrypt.png                              | Bin 100837 -> 60677 bytes
 images/heroku.png                               | Bin 10932 -> 10772 bytes
 images/hipchat_token_screen.png                 | Bin 76816 -> 42565 bytes
 images/hiro-hs.png                              | Bin 60825 -> 37729 bytes
 images/justine-hs.png                           | Bin 322170 -> 310461 bytes
 images/launchpad-slug.png                       | Bin 31209 -> 24796 bytes
 images/logo-engineyard.png                      | Bin 29711 -> 26032 bytes
 images/made-in-berlin-badge.png                 | Bin 10233 -> 6170 bytes
 images/new-tricks.png                           | Bin 411173 -> 242508 bytes
 images/nodejitsu.png                            | Bin 17291 -> 16740 bytes
 images/piotr-hs.png                             | Bin 253672 -> 237862 bytes
 images/saucelabs.png                            | Bin 13752 -> 4687 bytes
 images/screenshots/concurrent-builds-how-to.png | Bin 98018 -> 72071 bytes
 images/settings-env-vars.png                    | Bin 70509 -> 46219 bytes
 images/settings-ssh-key.png                     | Bin 59231 -> 30546 bytes
 images/srcclr-travis.png                        | Bin 65630 -> 35783 bytes
 images/stats.001.png                            | Bin 32082 -> 19756 bytes
 images/stats.002.png                            | Bin 25431 -> 12483 bytes
 images/stats.003.png                            | Bin 84480 -> 49684 bytes
 images/stats.004.png                            | Bin 60067 -> 35386 bytes
 images/stats.005.png                            | Bin 44422 -> 21299 bytes
 images/stats.006.png                            | Bin 34673 -> 21990 bytes
 images/stats.007.png                            | Bin 29936 -> 17758 bytes
 images/travis-branches.png                      | Bin 185944 -> 112985 bytes
 images/travis-loves-code-climate.png            | Bin 116581 -> 107608 bytes
 images/travis-mascot-200px.png                  | Bin 26534 -> 19381 bytes
 images/travis-mascot-400px.png                  | Bin 55579 -> 39162 bytes
 images/travis-mascot-600px.png                  | Bin 84151 -> 58373 bytes
 slate/source/images/logo.png                    | Bin 44115 -> 28712 bytes
```

This can help speed up the loading and save the bandwidth and save a little bit resource on server.

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
@MariadeAnton @BanzaiMan is there anything I can do to make it acceptable? Thanks.

**Comment by plaindocs** [comment]
I'll take a look at this this week.

**Comment by plaindocs** [comment]
Right, so it is actually lossless? I missed that first time round! Amazing, thank you. Would you mind merging in and compressing the two new cron images and I'll merge this asap. Thanks again.

**Comment by PeterDaveHello** [comment]
yes it's lossless, okay ... trying, there are some new pics need to be compressed also

**Comment by PeterDaveHello** [comment]
@plaindocs updated, please take a look, thanks!

**Comment by plaindocs** [comment]
Thanks a lot!

**Pull request merged**
