### PR TITLE
Link to the "Minimal and Generic" docs from the main "Languages" documentation page

### PR DESCRIPTION
**Pull request by DeeDeeG**
Hi folks. This change should allow navigating to the docs for "Minimal and Generic" images directly from the base "Languages" docs page. 

(i.e. from here: https://docs.travis-ci.com/user/languages/ to here: https://docs.travis-ci.com/user/languages/minimal-and-generic/)

## Context
- Follow-up to #1989 
- Addresses a [comment](https://github.com/travis-ci/docs-travis-ci-com/issues/910#issuecomment-446382310) in #910 (consider me +1 in agreeing with that comment.)

## Caveat
~~I'm not really sure if this works, I just sort of guessed this might be the right change. Happy to adjust if given feedback, or happy to have maintainers add commits to fix this if I can't manage that.~~

Edit: It does appear to work as intended, based on the auto-deployed site for this pull request. https://deploy-preview-2184--musing-lamport-7fb66c.netlify.com/ :tada: Still happy to make any adjustments requested by the team, or have other commits added to my `patch-1` branch if needed. :+1:

### CODE REVIEW

**Comment by plaindocs** [comment]
Hi @DeeDeeG yeah, this makes sense. 

What do you say to splitting it into two entries though? I think if we are adding them, that would be clearer, as regards sorting.

**Comment by plaindocs** [comment]
Good questions. 

1. Don't bother for now. 
2. You *could* but I think the context is useful. If you already know which is which you're probably not coming via the languages page anyway.

:+1:

**Comment by DeeDeeG** [comment]
I also noticed while looking over #1989 that the "Minimal and Generic" link is hard-coded into the [`_includes/sidebar.html`](https://github.com/travis-ci/docs-travis-ci-com/pull/1989/files#diff-88116a8ad5517e8b9bfd0e9911642382) file, but probably will be auto-included now that these are in the `_data/languages.yml` file.

So, probably would be neatest to remove the hard-coded entry and only use the auto-included ones.

**Comment by DeeDeeG** [comment]
Going to set this up to test locally to double-check some things before I update the branch.

**Comment by DeeDeeG** [comment]
I kind of like the "Minimal and Generic images" link at the bottom of the sidebar. But anyways, I think of two approaches to get rid of the repeated entries.

1) The "for loop" in `_includes/sidebar.html` could be adjusted to not add list items for "Generic" and "Minimal";That way only the hard-coded entry appears.
2) The hard-coded entry could just be deleted.

I'm not sure I'd be able to code up the for loop change, but I can definitely remove the hard-coded "Minimal and Generic images" link. Open to input as to which is best.

**Comment by DeeDeeG** [comment]
Here's a screenshot of what it looks like now: 

<details>
<summary>Screenshot (click to expand!)</summary>

Travis CI User Documentation Sidebar snippet showing the "Languages" subsection. "Minimal" and "Generic" are listed among the languages, and "Minimal and Generic images" is also present at the bottom of the list.


</details>

**Comment by DeeDeeG** [comment]
A third option would be to put Minimal and Generic together as the last entry of `_data/languages.yml` and we could even put it as `Minimal and Generic images`. Then we can delete the hard-coded entry in the sidebar and likely no-one will notice the sidebar change at all.

**Comment by DeeDeeG** [comment]
Otherwise, I am fine to just leave the sidebar stuff for a later day, and let you folks discuss and decide what to do about it separately from this Pull Request.

**Comment by DeeDeeG** [comment]
Updated sidebar screenshot:

<details>
<summary>Screenshot (click to expand!)</summary>

Travis CI User Documentation Sidebar showing the "Languages" subsection. "Minimal" and "Generic" are listed among the languages; There is no redundant "Minimal and Generic images" link. Both the "Minimal" and "Generic" links are simultaneously highlighted as "active."


</details>

**Comment by DeeDeeG** [comment]
Could maybe add in small text "(bash, sh, shell)" next to Minimal, similar to the small text "(with Node.js)" next to Javascript. 

(But I keep thinking of ways to make this simple PR complicated, so I'll stop coming up with new ideas for now.)

Basically I think this could be merged now, but there are some additional ideas I've mentioned; If anyone is interested, feel free to discuss further here, or move those to separate issues/prs. I'll wait to add anything until there's more comments/feedback about them here, if any. In any case, it's a pleasure to have the chance to improve the docs.

Best,

\- DeeDeeG

**Comment by plaindocs** [comment]
Hey @DeeDeeG 

Thanks for all your thoughts on this. I think the current status with deleted hard coded link and separate Minimal and Generic entries is ideal. 

Thanks for your help!

**Pull request merged**
