### PR TITLE
Elixir: info on handling different OTP versions

### PR DESCRIPTION
**Pull request by henrik**
Based on https://gist.github.com/BanzaiMan/3e6370cc0a1991d2d3c9

### CODE REVIEW

**Comment by henrik** [comment]
This specific example is not currently runnable (`The command "wget http://s3.hex.pm/builds/elixir/v1.2.zip" failed and exited with 8 during .`) but I guess it's still helpful as an example, until 1.2 is released. Though maybe we should mention that it doesn't currently work.

cc @ericmj, @BanzaiMan

**Comment by ericmj** [comment]
You can set `1.2.0-dev` as version and it will probably work.

**Comment by henrik** [comment]
@ericmj Hm, afraid not, http://s3.hex.pm/builds/elixir/v1.2.0-dev.zip also seems to be missing. http://s3.hex.pm/builds/elixir/master.zip works but that's a moving target.

No big deal – I don't need to run tests against it, just thought I'd capture this in Travis documentation.

**Comment by ericmj** [comment]
@henrik Right, sorry about that. There won't be a 1.2.0 build available until 1.2.0 is released, unless you use master of course which will give you 1.2.0-dev.

**Comment by BanzaiMan** [comment]
I have updated the Elixir doc to reflect the automatic OTP Release selection I've just deployed.

**Pull request merged**
