### PR TITLE
Use strings in Go version examples

### PR DESCRIPTION
**Pull request by BanzaiMan**
See https://github.com/travis-ci/travis-build/pull/1310#discussion_r169568253 for context.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Maybe it is worth noting that one should not use `1.10` (a string) in specifying Go 1.10.

**Comment by plaindocs** [comment]
You're saying double down on 

> you can use `"1.10"` but not `1.10`

?

**Comment by BanzaiMan** [comment]
Yes, that is what I mean.

**Comment by plaindocs** [comment]
Probably, given it comes up a lot. :+1:

**Comment by BanzaiMan** [comment]
building_a_go_project_-_travis_ci

**Comment by plaindocs** [comment]
:shipit:

**Pull request merged**
