### PR TITLE
Use .ruby-version file instead of ruby statement in Gemfile

### PR DESCRIPTION
**Pull request by igorwwwwwwwwwwwwwwwwwwww**

### CODE REVIEW

**Comment by plaindocs** [comment]
I can't find a reference for using `2.0.0` vs `ruby-2.0.0` but I'm happy to take your word on this :-p.

**Comment by plaindocs** [comment]
Do you want to delete `.ruby-version` from the ignore file and repush?

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
@plaindocs this patch already does that -- unless I'm misunderstanding your request.

**Comment by plaindocs** [comment]
You are entirely correct - a week of pycon has taken a bigger toll on my brain than I thought.

**Pull request merged**
