### PR TITLE
Added section about CatLight desktop notifications

### PR DESCRIPTION
**Pull request by catlightio**

### CODE REVIEW

**Comment by plaindocs** [comment]
Hi @catlightio,
 
Nice looking notifications there.

Could you move the PR to apply to `/user/apps.md` instead of `/user/notifications/`?  

Thanks! :-)

**Comment by catlightio** [comment]
Hi,

We think that seeing current build status on the desktop is the best way to stay notified. But, current documentation does not mention that, and suggests to use email or chat notifications. Travis also sends emails pointing to this notification page. Developers may think that those are the only ways to monitor continuous delivery.

Take a look at this post [comparing email and direct desktop notifications](http://blog.catlight.io/post/143100149238/one-icon-instead-of-1000-emails-keep-track-of). Chat notifications have pretty much the same problems as emails.

What do you think?

**Comment by plaindocs** [comment]
That is actually an interesting perspective.

I'll have a quick think about what the different in our historical use of third party apps vs notifications is.

Partly that might depend on how generic the configuration is, but if nothing else I can certainly look at cross mentioning / linking the notification page to the desktop notifications.

Reopening pending further investigation.

**Comment by catlightio** [comment]
Do you think it's worth a try? Lots of developers really enjoy using CatLight, and prefer it over email and chat notifications. See the score on [this StackOverflow answer](http://stackoverflow.com/questions/32776840/no-build-notifications-with-vs-2015/35595760#35595760). 

Other build systems also have it as a part of documentation. For example [Jenkins](https://wiki.jenkins-ci.org/display/JENKINS/Monitoring+Jenkins) and [Appveyor](https://www.appveyor.com/docs/notifications/#build-status-in-tray---catlight)

It's really a better way to engage the whole team in using Travis CI, and keeping their builds green.

**Comment by MariadeAnton** [comment]
Hi @catlightio,

Thanks so much for this, once this is fully set, we'll merge in :) 

Can you link back to our homepage and our docs page within https://catlight.io and https://catlight.io/a/travis-build-status-notifications ? 

If you prefer a specific trackable link, please use: 

* https://travis-ci.com/?utm_source=catlight&utm_medium=homepage →  if it comes from your homepage and so on :) 

Thank you!

**Comment by MariadeAnton** [comment]
Hi again, @catlightio ! We're closing this PR for now, please feel free to reopen if/when https://github.com/travis-ci/docs-travis-ci-com/pull/1031#issuecomment-371164475 are addressed. 

Thank you!

**Comment by catlightio** [comment]
I've added the direct link on https://catlight.io/a/travis-build-status-notifications . Homepage has a big Travis logo, leading to the integration page with a link. 

I wouldn't expect much traffic from it though. People come to our site to get a notifier for the system they already use.

**Comment by plaindocs** [comment]
Thanks!

**Pull request closed without merging**
