### PR TITLE
Styles for beta banner

### PR DESCRIPTION
**Pull request by lislis**
screen shot 2017-01-25 at 16 50 49
@plaindocs

### CODE REVIEW

**Comment by plaindocs** [comment]
Looks awesome. It does not scream out BETA to me though, so could be assumed just to be an "important note" ?

**Comment by lislis** [comment]
true. should we bring back the 'BETA'?

**Comment by plaindocs** [comment]
That is my next tshirt!

But yes i think so. :-D

**Comment by plaindocs** [comment]
Thanks @lislis ! :100: :tada:

**Pull request merged**
