### PR TITLE
Improve SonarQube set-up docs

### PR DESCRIPTION
**Pull request by 304NotModified**
Direct link to Repository Settings for saving SONAR_TOKEN

for page https://docs.travis-ci.com/user/sonarqube/

### CODE REVIEW

**Comment by plaindocs** [comment]
@304NotModified looks good - could you resolve the conflict so I can merge?

**Comment by 304NotModified** [comment]
sure, will do that this week.

**Comment by plaindocs** [comment]
Gentle reminder?

**Comment by 304NotModified** [comment]
thx, working on it :)

**Comment by 304NotModified** [comment]
Done (rebased)

**Comment by plaindocs** [comment]
Thanks!

**Pull request merged**
