### PR TITLE
Remove mention of a container-based Linux default

### PR DESCRIPTION
**Pull request by meatballhat**
since it is going away and the current default is in transition

### CODE REVIEW

**Comment by edmorley** [comment]
@meatballhat what will the new default be, out of curiosity? (And hi again!)

**Comment by edmorley** [comment]
Ah thank you!

**Comment by plaindocs** [comment]
I'd prefer to still explicitly mention a default, even if it is short term link to the blog post that we can switch out in a few weeks. What do you think @meatballhat ?

**Comment by acnagy** [comment]
@plaindocs would it be wrong to link to the blog post for the timeline for the transition? right now it's `.org` that's all vm-based, starting 🔜 `.com` default will move over with percent-based sampling. Thennnn.. there's a few weeks of "everyone hopefully updates their builds" then we start overriding `sudo: false` specifications

**Comment by plaindocs** [comment]
How about something like

> Between middle of October 2018 and end November 2018 the default infrastructure your builds runs on will depend on a [few different factors](https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures) while we consolidate everything onto sudo-enabled virtual machines. 

adjusting dates as needed. 

@acnagy as an aside, what do you think about using virtual machines in full in docs and blogs?

**Comment by acnagy** [comment]
@plaindocs sounds perfect to me. Re:dates - we're planning Oct 2018 - Dec 2018 (last overrides will run into December). 

As to "vms" vs. "virtual machines" vs. "sudo enabled" - yeah, def agreed we should use "virtual machine"... and now I realize I need to fix my blog post: "vm" --> "virtual machine" 😅

**Pull request merged**
