### PR TITLE
Add documentation on Google Chrome addon

### PR DESCRIPTION
**Pull request by BanzaiMan**
To correspond to https://github.com/travis-ci/travis-build/pull/1041.

### CODE REVIEW

**Comment by plaindocs** [comment]
I'd prefer to fold this into headless browsing rather than have a separate topic on the addon - what do you think?

**Comment by BanzaiMan** [comment]
Each addon should be documented separately. Adding mentions of Chrome in user/gui-and-headless-browsers.md is of course welcome.

**Comment by BanzaiMan** [comment]
It may make sense to move the "headless mode" section from this document to user/gui-and-headless-browsers.md.

**Comment by plaindocs** [comment]
@BanzaiMan I've taken the liberty of pushing some minor changes onto your branch. Please confirm and :ship: :it: .

**Pull request merged**
