### PR TITLE
Use the correct syntax for upload_dir in s3 deploy

### PR DESCRIPTION
**Pull request by hussfelt**
Hyphen is not supported, use underscore for correct configuration using upload_dir

### CODE REVIEW

**Comment by BanzaiMan** [comment]
This is not entirely accurate. We normalize the hyphens to underscores, so `upload-dir: foo` works fine.

**Comment by hussfelt** [comment]
Very strange!

All my builds failed using the dash, even my yml linting in sublime
complained. I changed it to underscore and everything passed.

Will try again tomorrow and attach any logs available!

On Wednesday, 28 October 2015, Hiro Asari <notifications@github.com> wrote:

> This is not entirely accurate. We normalize the hyphens to underscores, so upload-dir:
> foo works fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/travis-ci/docs-travis-ci-com/pull/409#issuecomment-151875210>
> .
>


-- 
Henrik Hussfelt

Mobile: +46 708 321 222
E-mail: henrik@henrik.se
http://hussfelt.net

**Comment by hussfelt** [comment]
@BanzaiMan very strange. I can't explain how this failed before.

Do consider merging this as well, together with the following PR's?
https://github.com/travis-ci/travis.rb/pull/334
https://github.com/travis-ci/travis.rb/pull/333

Just for readability and coherency as most of the other configuration-parameters has underscore instead of hyphens...

If not; Please do go ahead and close the other PR's in connection to this!

Thanks! :-)

**Comment by plaindocs** [comment]
Looks like I can close this. Please reopen if it is still an issue. Thanks.

**Pull request closed without merging**
