### PR TITLE
Update all the docs!

### PR DESCRIPTION
**Pull request by lislis**

### CODE REVIEW

**Comment by plaindocs** [comment]
:-)

**Comment by lislis** [comment]
@plaindocs I restored `user/build-configuration.md` Did I delete that by accident or did you intend to delete it and I just got confused by merging things?

**Comment by plaindocs** [comment]
Those merges get pretty ugly hey? :-p From memory I think I merged it with another build-config related topic. Probably `customizing-the-build.md` ?

**Comment by lislis** [comment]
@plaindocs ah yes, that looks very much like it. Then I delete `user/build-configuration.md` again

**Comment by roidrage** [comment]
OMG YAYAYAY!

**Pull request merged**
