### PR TITLE
Python docs revamp for compatibility with all distros

### PR DESCRIPTION
**Pull request by iriberri**
I did some extra reordering for the default/dev/nightly versions that were at the bottom of the document, since I believe it makes sense to have this together in the "specify your version" section.

### CODE REVIEW

**Comment by iriberri** [comment]
Just a comment (for myself, mostly) from something I just investigated: nosetests *is* available in the new images too.

**Comment by plaindocs** [comment]
Hey @iriberri I added `trusty_note_no_osx` to the snippets now.

**Comment by iriberri** [comment]
Not sure why tests are failing:

```
- ./_site/user/integration/platformio/index.html
  *  linking to /user/languages/python/#Travis-CI-Uses-Isolated-virtualenvs, but Travis-CI-Uses-Isolated-virtualenvs does not exist (line 369)
     <a href="/user/languages/python/#Travis-CI-Uses-Isolated-virtualenvs">Travis CI
```

image

**Comment by iriberri** [comment]
After playing with `pip list`, the list of pre-installed packages is ready now.

@plaindocs this is ready for review :)

**Comment by iriberri** [comment]
Hi @plaindocs, I just pushed the following:

* Edited the table to mention "Default" instead of "typical". Totally 👍 about this, I didn't notice the change.
* Moved the info on default Python version from the language page to both Trusty and Precise pages.

**Comment by iriberri** [comment]
I'm working on a couple more updates to make sure we follow the Dependency Management & Default Build Script here.

**Comment by plaindocs** [comment]
I *like* the comments in the yaml example!

**Comment by iriberri** [comment]
Ouch, I totally missed to apply the `{: data-file=".travis.yml"}`. Thanks for the fixes @plaindocs :)

**Comment by MariadeAnton** [comment]
Nice and shiny 💯

**Pull request merged**
