### PR TITLE
Add description of where to contribute

### PR DESCRIPTION
**Pull request by niccokunzmann**
Problem: I want to get the code, know where it is and contribute.
Solution: Add a description of where I can find it.

You can help me telling me the link or adding the link. I was searching for 10 minutes and I could not find the implementation.

### CODE REVIEW

**Comment by plaindocs** [comment]
All deployment implementation is in https://github.com/travis-ci/dpl/

I'll see if adding the link to each deployment in the would be useful to the majority of readers.

**Comment by niccokunzmann** [comment]
Thanks! Maybe it could also be useful for the projects.

**Comment by niccokunzmann** [comment]
Thanks! Maybe it could also be useful for the projects.

**Comment by plaindocs** [comment]
I think as the majority of readers won't want to make pull requests to `dpl` itself I'll close this for now.

**Pull request closed without merging**
