### PR TITLE
Corrected port for vhost in php documentation

### PR DESCRIPTION
**Pull request by danrot**
This caused me some trouble, it seems like the given port in the vhost configuration file is 8080 instead of 80.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Could you point to the build URLs (one that doesn't work, and one that does) that explains this issue? Thank you.

**Comment by danrot** [comment]
Sry, I can't find the build URLs anymore... however, I am talking about this line: https://github.com/sulu-io/sulu-standard/pull/517/files#diff-7bde54db60a6e933518d8b61b929edceR117

It has to be 8080 in order to work, and even if I output the configuration file using `cat` it displays a file listening to port 8080 instead of 80.

**Comment by danrot** [comment]
ping

**Comment by BanzaiMan** [comment]
What do you mean by "in order to work"? How does it fail?

**Comment by danrot** [comment]
I've already explained that previously, what's not clear about it? You can also check the given file i have edited in the documentation. You'll see that the actual value of the port in the vhost config file is 8080 instead of 80.

**Comment by danrot** [comment]
I've already explained that previously, what's not clear about it? You can also check the given file i have edited in the documentation. You'll see that the actual value of the port in the vhost config file is 8080 instead of 80.

**Pull request closed without merging**
