### PR TITLE
Update open-source-on-travis-ci-com.md

### PR DESCRIPTION
**Pull request by Zearin**

### CODE REVIEW

**Comment by plaindocs** [comment]
Hi @Zearin 

Thanks for these changes. I don't really mind either way about the line breaks, but your link syntax isn't working. See the preview here https://deploy-preview-1883--musing-lamport-7fb66c.netlify.com/user/open-source-on-travis-ci-com/ 

We're using Kramdown https://kramdown.gettalong.org/syntax.html#reference-links

**Comment by Zearin** [comment]
Whoops.  That’s what I get for renaming the branch!    (I’ll reopen shortly.)

@plaindocs I’ve looked at the Kramdown reference you linked. I couldn’t see anything that indicated reference-style links would not work.  Stumped, I checked the preview you linked… and the links are all working for me.  Can you double-check the links in the preview?

**Comment by plaindocs** [comment]
Hey Zearin, yeah you're right, ref styles does work in Kramdown. Not sure what was going on first time I looked. 

Merging in.

**Comment by plaindocs** [comment]
Ooh, my mistake. I'll merge into `master`.

**Pull request merged**
