### PR TITLE
Add documentation for Perl 6

### PR DESCRIPTION
**Pull request by paultcochrane**
This is the documentation to accompany the community-supported Travis build for Perl 6 (see https://github.com/travis-ci/travis-build/pull/415).

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Is there a PR for https://github.com/travis-ci/travis-core that enables matrix expansion on Perl 6 versions? See http://docs.travis-ci.com/user/languages/community-supported-languages/#Code

**Comment by BanzaiMan** [comment]
Pushing this one more day while we wait for the matrix support.

**Comment by paultcochrane** [comment]
@BanzaiMan sorry, I wasn't aware that one needed to patch travis-core as well.  Hence, no, there isn't a PR for travis-core enabling matrix expansion on Perl6 versions, however it is forthcoming.

I just tried using the merged `perl6` language option on one of my repositories, however it didn't select `perl6` at all and ran Ruby.  What am I missing in order to test the new functionality?  Is it at all possible to test matrix expansion on a local testing environment?  Or is it necessary to build and test in the staging environment?

**Comment by paultcochrane** [comment]
Perl6 matrix expansion support has been added in https://github.com/travis-ci/travis-core/pull/462.

**Comment by BanzaiMan** [comment]
@paultcochrane The Perl 6 support is out, but the matrix is not showing the language value; could you create a PR for travis-web as well?

Thanks!

**Comment by paultcochrane** [comment]
@BanzaiMan sure, here 'tis: https://github.com/travis-ci/travis-web/pull/366

**Comment by paultcochrane** [comment]
@BanzaiMan two issues.  One major, one not quite so major.

1. the Perl6 version being selected as part of the build script is coming out as `[<version-number>]` and not simply `<version-number>`.  It looks like an array is being converted to a string representation in the Ruby processing the build.  I'm not sure what's causing the problem.  Do you have a tip as to what could be causing the problem?  Would it be possible for me to debug the issue and run tests of the build script within the Travis staging environment?  If so, how do I do this?
2. is it possible to update the blog entry text?  There's a grammatical error in the first sentence, however the sentence is unfortunately also inaccurate (Perl 6 isn't an update to Perl 5; it's a "sister language").  Note also that "candidate" is spelled incorrectly in the second sentence.  Hence, could you please update the text to the following?:

"""
Perl 6 is the next generation in the family of Perl programming languages, and a sister language to the well-established Perl 5. With a release candidate expected in September, and the first release by December, it's a great time to start testing your Perl 6 programs.
"""

Many thanks!

**Comment by paultcochrane** [comment]
@BanzaiMan I've worked out what the problem was in item 1. above: I was using strings for the version numbers, e.g. `perl6: "2015.05"`.  Strangely enough, this works in Perl 5...

The issues with the blog entry text are however important.  Would it be at all possible to update the text, please?

Thanks!

**Comment by BanzaiMan** [comment]
@paultcochrane I'm not quite sure what problems you saw with regards to the issue 1. Do you have a build log URL that shows the problem?

You are welcome to open a new PR to suggest further edits.

**Pull request merged**
