### PR TITLE
Show 5 latest Node.js releases

### PR DESCRIPTION
**Pull request by BanzaiMan**

### CODE REVIEW

**Comment by plaindocs** [comment]
@BanzaiMan do you mind resolving?

I'm excited about automating more of these version numbers.

**Comment by BanzaiMan** [comment]
Netlify doesn't seem to work with dynamic content like this, though. Am I right?

**Comment by plaindocs** [comment]
Yeah, it should.

It *might* not be working due to how we set the Rake tasks up though. If that is the case, good you noticed.

**Comment by BanzaiMan** [comment]
I'll go ahead and merge this. We'll look at Netifly issue separately.

**Pull request merged**
