### PR TITLE
Add "CI for Embedded Platforms" guide

### PR DESCRIPTION
**Pull request by ivankravets**
Continuous Integration for Embedded Platforms using @PlatformIO ( http://platformio.org )

### CODE REVIEW

**Comment by plaindocs** [comment]
I'll take a look at this and edit to bring it a bit closer to the rest of the docs. Thanks!

**Comment by ivankravets** [comment]
@plaindocs Thanks! Don't hesitate contact me if you have any questions.

**Comment by ivankravets** [comment]
@plaindocs do you need any help?

**Comment by plaindocs** [comment]
Hi @ivankravets sorry about the delay on this.

I've pushed up two commits to https://github.com/travis-ci/docs-travis-ci-com/tree/ivankravets-gh-pages:

14cea21
5be0c9e

Long story short, I've moved the doc into the deployment section, reworded some of the text, and shortened some of the lists of supported boards etc. Feel free to comment inline, or just merge the text into your PR and I'll merge that asap.

Thanks!

**Comment by ivankravets** [comment]
Dear @plaindocs,

I've just merged your changes and corrected popular frameworks and platforms.

Nevertheless, I see that you renamed it to "PlatformIO Deployment" and moved to deployment section. However, @PlatformIO isn't suitable for deployment. It will confuse @travis-ci users. This is instrument with independent tool chains, frameworks and etc.

To my mind, this is clear for embedded developers `<li><a href="/user/ci-embedded-platforms/">CI for Embedded Platforms</a></li>`.

This pull is more closer to https://docs.travis-ci.com/user/docker/ then to https://docs.travis-ci.com/user/deployment/

Thanks!

**Comment by ivankravets** [comment]
Deployment makes sense for @PlatformIO if @travis-ci will upload firmware to the user's hardware :smile: However, it is impossible.

**Comment by plaindocs** [comment]
Thanks! I'll check with the rest of the team on Tuesday, and we'll get this up one way or another.

**Comment by ivankravets** [comment]
@plaindocs do you have any news?

**Comment by plaindocs** [comment]
Merging that today after making a few changes.

**Comment by ivankravets** [comment]
@plaindocs thanks a lot! Will forward users to new documentation!

**Pull request merged**
