### PR TITLE
Update hosts.md - make clear where names resolve

### PR DESCRIPTION
**Pull request by tdmalone**

### CODE REVIEW

**Comment by plaindocs** [comment]
Thanks for that. Do you want to add the IPv6 equivalent as well for completeness. `::1` ?

**Comment by BanzaiMan** [comment]
@plaindocs The addon does not affect `::1`.

**Comment by plaindocs** [comment]
Thanks @BanzaiMan ! So then we need to remove mention of IPv6 above, right?

**Comment by BanzaiMan** [comment]
@plaindocs Indeed. (It was removed in https://github.com/travis-ci/travis-build/pull/817 last year.)

**Comment by plaindocs** [comment]
Thanks @tdmalone !

**Pull request merged**
