### PR TITLE
Fix up the docker instructions

### PR DESCRIPTION
**Pull request by plaindocs**
Fix for #900

* [ ] what is the difference between garnet and amethyst 
* [ ] Is the PID instruction valid for both 
* [ ] the docker command still references quay, so we need one for trusty also

@MariadeAnton @iriberri any more thoughts and suggestions?

### CODE REVIEW

**Comment by MariadeAnton** [comment]
Hi @plaindocs, sorry for the delay!

Here I come with some possible answers: 

Currently, container-based images available goes as documented: 

- `sudo: false` container-based Precise images are available at https://quay.io/organization/travisci
- `sudo: false` container-based Trusty images are available at https://hub.docker.com/r/travisci/

For the Trusty ones, both garnet and amethyst overlap a lot, but we tag them specifically for languages: 

- Garnet:  https://github.com/travis-ci/packer-templates/blob/master/cookbooks/travis_ci_garnet/attributes/default.rb#L126-L143

    -   c
    -   c++
    -   clojure
    -   cplusplus
    -   cpp
    -   default
    -   go
    -   groovy
    -   java
    -   node_js
    -   php
    -   pure_java
    -   python
    -   ruby
    -   scala

- Amethyst: https://github.com/travis-ci/packer-templates/blob/master/cookbooks/travis_ci_amethyst/attributes/default.rb#L125-L138

    -   crystal
    -   csharp
    -   d
    -   dart
    -   elixir
    -   erlang
    -   haskell
    -   haxe
    -   julia
    -   perl
    -   r
    -   rust

As for the PID instructions, I'm not sure atm, sorry!

**Comment by BanzaiMan** [comment]
See also https://github.com/travis-ci/docs-travis-ci-com/pull/1159. I'll also devise a way to update this file automatically with the image name and the tag for Trusty images.

**Comment by BanzaiMan** [comment]
The PR above resolves all the concerns raised by @plaindocs.

**Comment by BanzaiMan** [comment]
Oh. Right. I'm closing this, in favor of #1159.

**Pull request closed without merging**
