### PR TITLE
making ataglance minimal examples as minimal as possible

### PR DESCRIPTION
**Pull request by PatMyron**
Python is the only language without a default script in its at-a-glance side panel. Should Python's script default to `pytest`?

### CODE REVIEW

**Comment by plaindocs** [comment]
Nope, python is special like that.

> If you do not provide a script key in a Python project, Travis CI prints a message (“Please override the script: key in your .travis.yml to run tests.”) and fails the build.

**Comment by PatMyron** [comment]
@plaindocs Sorry, that was unclear. I meant should the actual behavior itself be changed to run `pytest` as the default script for Python?

**Comment by plaindocs** [comment]
I know enough python projects using makefiles that ancecdatally it doesn't seem default enough. But no reason for it not to detect Makefile and pytest like other languages.

**Comment by PatMyron** [comment]
@plaindocs makes sense. Fixed the merge conflicts

**Comment by plaindocs** [comment]
Perfect! merging. 

I've opened the Python thing for wider discussion at https://travis-ci.community/t/detect-python-defaults-opinions-wanted/2236 . Cheers!

**Comment by PatMyron** [comment]
@plaindocs could be worth analyzing public Github repositories to get a better understanding of the breakdown. I might look into it sometime

**Pull request merged**
