### PR TITLE
fix current page highlighting

### PR DESCRIPTION
**Pull request by lislis**
The old implementation did not consider being directly linked to a page which
led to inconsistent behaviour

### CODE REVIEW

**Comment by plaindocs** [comment]
This does not seem to fix the problem for me, in Chrome on Linux. 

screenshot from 2016-07-29 17 08 11

**Comment by plaindocs** [comment]
Also - would it make sense to be able to click the open title to close it? or should that be a separate bug? :-p

**Comment by lislis** [comment]
Oh wow. Seems like there is another component to this that I haven't though about :/
Thanks for properly testing 💃 I'll have another look next week

**Comment by lislis** [comment]
@plaindocs I think I got the cause for the bug with the double highlighting. It should work now, but let me know (as usual) if you encounter another bug

**Comment by plaindocs** [comment]
Thought I'd merged this already, oops. Looks awesome though, thanks!

**Pull request merged**
