### PR TITLE
Add Windows to trusty_note

### PR DESCRIPTION
**Pull request by Mizux**
To get a link to windows here:
https://docs.travis-ci.com/user/languages/cpp/#what-this-guide-covers
since it should support cpp too

### CODE REVIEW

**Comment by plaindocs** [comment]
Ooh, wait a minute, I may have been too hasty in merging this. This snippet is reused in many languages, only some of which have the same availability. :thinking:

**Comment by Mizux** [comment]
Then it's start to rework all snippet and change naming.
`trusty_note` -> `all_note`; `all_note_no_osx`; `linux_note` **or**  `all_note_no_osx_no_win`

**Comment by Mizux** [comment]
FYI:
%grepc -rin "trusty_note[^_]" .  
./user/languages/c.md:31:{{ site.data.snippets.trusty_note }}
./user/languages/java.md:28:{{ site.data.snippets.trusty_note }}
./user/languages/javascript-with-nodejs.md:33:{{ site.data.snippets.trusty_note }}
./user/languages/cpp.md:30:{{ site.data.snippets.trusty_note }}
./user/languages/ruby.md:34:{{ site.data.snippets.trusty_note }}
./user/languages/rust.md:29:{{ site.data.snippets.trusty_note }}
./_data/snippets.yml:26:trusty_note: |

**Comment by plaindocs** [comment]
Yep - it gets pretty messy pretty quick. I'll cherry pick that commit back onto a branch and have another look.

**Comment by Mizux** [comment]
@plaindocs Just to get an update, since you revert this merge we still not see windows link in C++ page
see https://docs.travis-ci.com/user/languages/cpp/  so what's the plan next ?

**Pull request merged**
