### PR TITLE
add ruby 2.3.x support info

### PR DESCRIPTION
**Pull request by lucianosousa**

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Thanks for the PR.

Please keep in mind that 2.3 is not yet available pre-installed on all images.

**Comment by plaindocs** [comment]
Cheers @BanzaiMan , I was just checking that.

**Comment by lucianosousa** [comment]
Cheers guys! I've few projects on it and looks like they already have this support.
Let's wait till it

**Comment by plaindocs** [comment]
Thanks for your work on this. I'm closing this PR as we've refactored Ruby version info into the infrastructure pages in https://github.com/travis-ci/docs-travis-ci-com/pull/1312

**Comment by lucianosousa** [comment]
Awesome! You are welcome

**Pull request closed without merging**
