### PR TITLE
Document workaround for PHPUnit on HHVM

### PR DESCRIPTION
**Pull request by bogdanap**
References: 
- https://github.com/travis-ci/travis-cookbooks/issues/908
- https://github.com/travis-ci/travis-ci/issues/8516#issuecomment-332979598

Since we didn't think it's worth downgrading PHPUnit, documenting the workaround seems like a good middle ground.

### CODE REVIEW

**Comment by plaindocs** [comment]
Hi @bogdanap ,

Cheers for this. Couple of comments:

What do you thing about removing 

> +In order to do that, you can add the following bit to your `.travis.yml`: 

And instead
 
> Please note that if you want to run PHPUnit on HHVM, you have to explicitly install version 5.7 in your `.travis.yml` due to a compatibility issue between HHVM and PHP7:

Also you can add `{: data-file=".travis.yml"}` immediately after the code block. 

Finally, does it make more sense to add this to the HHVM section, the PHPUnit section, or possibly even both instead of just throwing it onto the end?

**Comment by bogdanap** [comment]
@plaindocs Thank you for the suggestions - I've tried to implement them, so please feel free to take another look 😄

**Comment by plaindocs** [comment]
Perfect, thanks! :-)

**Comment by uglyoldbob** [comment]
I needed to use `curl -sSLf -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar` to get it to work

**Pull request merged**
