### PR TITLE
Rethink FAQs

### PR DESCRIPTION
**Pull request by plaindocs**
I'd like to fix up how we treat FAQs. We currently have:

* Common Questions in `index.html`
* The Pro FAQ `/user/travis-pro/`
* Common Build Problems `/user/common-build-problems/`
* Build FAQ `/user/customizing-the-build/#Build-FAQ`

This cannot continue! :-p

I propose moving, renaming and finding a proper home for everything in the list above (with the possible exception of the last one, which works in the context of Build Customization).

Then adding a root `FAQ.md` which is just a list of links, which support can update as needed to highlight  things which are cropping up a lot (along with a commitment to keep it up to date? :-p). 

FAO @MariadeAnton @sinthetix

### CODE REVIEW

**Comment by plaindocs** [comment]
Please ignore the spurious first commit re nodejitsu

**Comment by joshk** [comment]
:+1:

**Comment by sinthetix** [comment]
:+1: :+1: :+1: would merge if there was anything to merge. :wink: :sparkling_heart:

**Comment by plaindocs** [comment]
@joshk Now that caching is also available on container based infrastructure, I'm planning to move that topic into the main menu, and consolidate Travis Pro FAQ and Private Dependencies into a single Pro topic (also in the main menu.

**Comment by joshk** [comment]
As long as it isn’t called `Travis Pro FAQ`, sounds great to me! :)

**Comment by plaindocs** [comment]
I was thinking of "The Supreme Collection of all the best and most useful articles about Travis PRO and some FAQ". That work for you?

**Comment by joshk** [comment]
Hmmmmm, close.




Just change `PRO` for `Travis CI for Private Projects`

**Comment by MariadeAnton** [comment]
@plaindocs: great work!

**Comment by plaindocs** [comment]
@MariadeAnton shipit whenever you like and I'll push more as I work on adding FAQs.

**Comment by plaindocs** [comment]
OK, there is the Docker stuff, with Trusty removed for now. I'm not entirely happy with the last couple of lines, but in the interests of putting the info up, I'd say ship it. Suggestions for improvements welcome.

**Comment by plaindocs** [comment]
For future reference: 

### Running an Ubuntu Trusty Based Docker Image Locally

1. Download and install the Docker Engine:
  * [Windows](https://docs.docker.com/installation/windows)
  * [OS X](https://docs.docker.com/installation/mac)
  * [Ubuntu Linux](https://docs.docker.com/installation/ubuntulinux/)
2. Open a terminal and run an interactive Docker session using the image URL:

   ```bash
   docker run -it travisci/ci-mega:packer-1446422932
 /bin/bash
   ```

3. Switch to the `travis` user:

   ```bash
   su - travis
   ```

3. Clone your git repository into the `/` folder of the image.
4. Manually install any dependencies.
5. Manually run your Travis CI build command.

**Comment by plaindocs** [comment]
And broken build is non related.

**Pull request merged**
