### PR TITLE
Add pre-release option for GitHub Releases Uploading

### PR DESCRIPTION
**Pull request by h2so5**
Refer to https://github.com/travis-ci/dpl/issues/234.

### CODE REVIEW

**Comment by h2so5** [comment]
@BanzaiMan That's weird. I tried this option and it seemed to work properly.

**Comment by BanzaiMan** [comment]
This feature does not exist, as far as I know.

**Comment by BanzaiMan** [comment]
Hmmm. Do you have a build log URL that shows this feature exists?

**Comment by h2so5** [comment]
@BanzaiMan I made a testing repo.

https://github.com/h2so5/prerelease-test
Releases: https://github.com/h2so5/prerelease-test/releases
Commits: https://github.com/h2so5/prerelease-test/commits/master
Deploy logs: https://travis-ci.org/h2so5/prerelease-test

**Comment by MariadeAnton** [comment]
Thanks for all the extra info, @h2so5 - it seems this behaviour is not consistent across triggered releases, sorry!

We're holding this until the fully built-in feature exists https://github.com/travis-ci/dpl/issues/234

**Pull request closed without merging**
