### PR TITLE
handle tests written with the new test package

### PR DESCRIPTION
**Pull request by a14n**

### CODE REVIEW

**Comment by a14n** [comment]
/cc @devoncarew @sethladd @kevmoo for review

Related to travis-ci/travis-build#525

**Comment by kevmoo** [comment]
@BanzaiMan help with this and travis-ci/travis-build#525 ?

**Comment by a14n** [comment]
Friendly reminder.
As travis-ci/travis-build#525 has been merged it's worth it to keep doc up to date.

**Comment by plaindocs** [comment]
Thanks!

**Pull request merged**
