### PR TITLE
Update manual build information

### PR DESCRIPTION
**Pull request by mgaudet**
Today, you need to specify a tag explicitly

### CODE REVIEW

**Comment by plaindocs** [comment]
Hi @mgaudet thanks for your work on this! Would you be able to switch the PR to the branch in https://github.com/travis-ci/docs-travis-ci-com/pull/1035 `sw-docker` ?

**Comment by mgaudet** [comment]
@plaindocs Just to clarify, you want this PR to go to travis-ci:sw-docker? (I'll rebase when I get to work assuming this is the case)

**Comment by plaindocs** [comment]
Yeah, that would be awesome! I've already done some work clarifying the instructions there, so with your update we'll have a much better doc.

**Comment by mgaudet** [comment]
Ok. Will do -- it'll be a couple hours, but I'll poke this issue when it's done.

**Comment by mgaudet** [comment]
Rebased change on travis-ci:sw-docker.

**Comment by plaindocs** [comment]
Ah, thanks. That was not quite what I expected. I'd you'd merge your updates into mine rather than clobber my changes entirely.

**Comment by mgaudet** [comment]
Oh! That's more a screwup on my part. I thought I saw only format changes -- lemme take another stab (being more careful this time).

**Comment by mgaudet** [comment]
Ok. I took a look at the patch, and I think it's better now. The big thing I forgot to do after rebasing was to change the pull request target branch, which is why the diff looked wrong.

**Comment by BanzaiMan** [comment]
Hi, @mgaudet Thanks for the contribution. I would like to close this in favor of my PR, #1159. I also plan to add how to map the language to the Trusty image on Docker Hub.

**Comment by mgaudet** [comment]
Sure. We can close this.

**Pull request closed without merging**
