### PR TITLE
contributed

### PR DESCRIPTION
**Pull request by bnhassin**
[Update](https://github.com/bnhassin/docs-travis-ci-com/tree/patch-1) open source guidelines on travis-ci-com.md

### CODE REVIEW

**Comment by bnhassin** [comment]
Referenced #2018 to assignee @bnhassin comments

**Comment by BanzaiMan** [comment]
I'm sorry, but what is this PR trying to address?

**Comment by bnhassin** [comment]
@BanzaiMan Thanks for mentioned
Using required services for deployed


Le vendredi 14 septembre 2018, Hiro Asari <notifications@github.com> a
écrit :

**Comment by BanzaiMan** [comment]
I'm sorry, but I don't see any meaningful change in this PR. It's an empty file and a renamed file that removes an existing document.

Did you forget to add something?

**Comment by bnhassin** [comment]
[Built Result on Travis-ci.com] (https://travis-ci.org/travis-ci/docs-travis-ci-com/jobs/429327339.patch)

**Comment by BanzaiMan** [comment]
Sorry, but I still don't see the aim of this PR. It adds a meaningless file, and it hides a meaningful document from view.

I'm closing this now, but do let us know if you feel otherwise strongly.

**Comment by bnhassin** [comment]
No release found in this forked, i so happy to connect with Travis-ci enjoying team

**Pull request closed without merging**
