### PR TITLE
Mark beta features like this going forward

### PR DESCRIPTION
**Pull request by plaindocs**
As mentioned in #918

After grepping our markdown I don't think we have many features in beta currently in the docs, apart from from some trusty stuff. @MariadeAnton am I missing anything?

### CODE REVIEW

**Comment by MariadeAnton** [comment]
@plaindocs cron jobs! turns out they' could use a beta notice and a link to https://github.com/travis-ci/beta-features/issues/1 :)

So yes, Trusty and Cron jobs 👍

**Comment by plaindocs** [comment]
@MariadeAnton wanna see if you have anything to add and merge if not.

**Comment by MariadeAnton** [comment]
💯  Thanks for the work on this @lislis and @plaindocs!

**Comment by plaindocs** [comment]
:sun_with_face:

**Pull request merged**
