### PR TITLE
Update csharp docs: dotnet sdk version, distributive

### PR DESCRIPTION
**Pull request by alexandrnikitin**
* Update .NET Core SDK version to the latest LTS as per https://github.com/dotnet/core/blob/master/release-notes/download-archive.md
* Remove notes about `trusty` distributive as it's default now

### CODE REVIEW

**Comment by plaindocs** [comment]
@joshua-anderson, @akoeplinger or @nterry review please?

**Comment by alexandrnikitin** [comment]
It's worth to mention that `1.0.3` sdk fails with `E: Unable to locate package dotnet-dev-1.0.3` example:
https://travis-ci.org/nsubstitute/NSubstitute/jobs/309772218#L436

**Comment by akoeplinger** [comment]
@alexandrnikitin 1.0.3 is no longer supported in the MS package repositories, I don't think we need to mention it.

**Comment by alexandrnikitin** [comment]
@akoeplinger Yes, I meant that. The PR removes `1.0.3` from the docs. Sorry for confusion 😊

**Comment by MarkHerhold** [comment]
I wasted a lot of time trying to figure out why `1.0.3` didn't work... I can confirm that `1.1.5` works well for me.

For other folks, this was the error I was getting:
```
E: Unable to locate package dotnet-dev-1.0.3
E: Couldn't find any package by glob 'dotnet-dev-1.0.3'
E: Couldn't find any package by regex 'dotnet-dev-1.0.3'
```

**Comment by plaindocs** [comment]
Thanks @alexandrnikitin @akoeplinger

**Pull request merged**
