### PR TITLE
Add HTML-Proofer

### PR DESCRIPTION
**Pull request by gjtorikian**
I discovered with the recent site refresh that some previous links were broken. For example, `http://docs.travis-ci.com/user/build-configuration/#White--or-blacklisting-branches` now resides at `http://docs.travis-ci.com/user/customizing-the-build/#Whitelisting-or-blacklisting-branches`. 

In order to prevent this in the future, I've added a documentation test suite by way of [html-proofer](https://github.com/gjtorikian/html-proofer/). We use html-proofer at GitHub to keep [our Jekyll/Pages accurate](https://github.com/blog/1939-how-github-uses-github-to-document-github#testing-our-site). Perhaps you too could hook it up to your favorite CI system? :wink: 

Along the way I started fixing some issues:

* Asset paths were being created in a weird way, so I removed `prepend` in favor of directly adding `{{ site.baseurl }}`.
* I added an `alt` tag to the footer logo (html-proofer complains about this by default)

There seem to still be quite a few broken links (for example, `/blog.xml` is referenced, but goes nowhere). I'm more than happy to keep going fixing these things, but I thought it best to open the PR now and get feedback as to whether this is something y'all are interested in.

### CODE REVIEW

**Comment by plaindocs** [comment]
This is awesome stuff. I looked at html-proofer a while back but never quite finished it.
I'll have a look at this and merge it in.

**Comment by gjtorikian** [comment]
Hello, @plaindocs! I'm at a conference in Prague with @MariadeAnton and was reminded of this issue. I was motivated to finish up the work I started, so during some downtime I cleaned up all the other issues I found. To give a quick summary:

* The most common issue I think were missing `alt` tags on images (examples: https://github.com/gjtorikian/docs-travis-ci-com/commit/d38ec2dee2b1eed7ea5c1051d429b3e78d44fc27, https://github.com/gjtorikian/docs-travis-ci-com/commit/839976c745880f938028567560e6cdc5e731b6f3), which is important for accessibility.
* Some internal links simply did not exist (examples: https://github.com/gjtorikian/docs-travis-ci-com/commit/55841a933515e6a626abbf5ddeb23d688256f4bc, https://github.com/gjtorikian/docs-travis-ci-com/commit/e40da79b58166be315bfa89ba26e5525cddfd376)
* Some internal links were renamed to avoid a redirect (example: https://github.com/gjtorikian/docs-travis-ci-com/commit/d68026c516fdbe76b99fd2264e0f5e8a160668a3).

Something that's also good news (for me): this PR revealed [a bug in `html-proofer`](https://github.com/gjtorikian/html-proofer/pull/238), which I fixed in the upstream project.

Let me know if I can provide more context/reasons for specific changes. Thanks!

**Comment by plaindocs** [comment]
Awesome, I'll merge this in now, and fix the few outstanding issues reported by proofer before hooking it up to some kind of continuous integration thingie. :-p

Thanks again for the hard work!

**Comment by plaindocs** [comment]
Now I've merged it, couple of questions (oops):

* you did not add a `.travis.yml`, intentionally?
* any idea what Proofer means with
    ```
    *  External link http://www.erlang.org/download.html failed: 0 No error
    ```

**Comment by gjtorikian** [comment]
Thanks!

> you did not add a .travis.yml, intentionally?

Yeah. I figured it was pointless for me to do so, since I'm not part of the org, and therefore wouldn't be able to configure Travis anyway. Here's an example from [the Raspberry Pi documentation](https://github.com/raspberrypi/documentation/blob/369c0a1ff69a9ecc25b545e25f1eab715801bdfd/.travis.yml) though.

> any idea what Proofer means with

Seems like the site might've been temporarily down? `0` is supposed to be [the error status code](http://stackoverflow.com/questions/3825581/does-an-http-status-code-of-0-have-any-meaning).

**Comment by plaindocs** [comment]
Yeah, figures. 

I've tied it all in, and after intentionally ignore a few things I know are broken we're green and good to go! Next step to add icons and what not to the README etc. :-)

**Pull request merged**
