### PR TITLE
Fix artifacts addon minimal configuration example

### PR DESCRIPTION
**Pull request by cdaguerre**
Fixes https://github.com/travis-ci/artifacts/issues/57

### CODE REVIEW

**Comment by brauliobo** [comment]
could you please include a reference to `ARTIFACTS_REGION` variable?

**Comment by cdaguerre** [comment]
@brauliobo WDYT?

**Comment by brauliobo** [comment]
nice :D

**Comment by plaindocs** [comment]
Thanks!

**Pull request merged**
