### PR TITLE
Ruby 2.0.c  ->  2.0.0

### PR DESCRIPTION
**Pull request by amatsuda**
Maybe you meant 2.0.x?
But actually we're not gonna make any other 2.0 release than 2.0.0, so this doesn't have to be 2.0.x.
Let it just be 2.0.0 here.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Indeed, it should've been `2.0.x`. But we'll accept `2.0.0` and be done with it.

Thanks for your eagle eyes! <3

**Comment by amatsuda** [comment]
Actually I was reading this document because I realised that giving 
`    - rvm: 2.2`
picks version 2.2.0, not 2.2.1, where it supposed to work as "2.1".
Should I better raise another issue, or could you look at it?

**Comment by BanzaiMan** [comment]
Indeed, `2.2` is currently an alias to `2.2.0`. This will change with the build environment update next month.

**Comment by amatsuda** [comment]
Understood. I'll do `2.2.1` then. Thanks for clarifying this!

**Pull request merged**
