### PR TITLE
Add activation step to directions

### PR DESCRIPTION
**Pull request by peeter-piegaze-sonarsource**
Add an explicit step about activating your repository on Travis, with a link to the tutorial.

### CODE REVIEW

**Comment by saadbitcoin** [comment]
From 7845edfc72222aecb35a25282feb714675a5dd0a Mon Sep 17 00:00:00 2001
From: Peeter Piegaze
 <61758048+peeter-piegaze-sonarsource@users.noreply.github.com>
Date: Mon, 1 Feb 2021 14:34:47 +0100
Subject: [PATCH] Add activation step to directions

Add an explicit step about activating your repository on Travis, with a link to the tutorial.
---
 user/sonarcloud.md | 11 ++++++-----
 1 file changed, 6 insertions(+), 5 deletions(-)

diff --git a/user/sonarcloud.md b/user/sonarcloud.md
index c6fb6494ac..4b6e2faf0f 100644
--- a/user/sonarcloud.md
+++ b/user/sonarcloud.md
@@ -18,16 +18,17 @@ The default Travis dist
 dist: xenial
 ```
 {: data-file=".travis.yml"}
-inlcudes Java 11 by default.
+includes Java 11 by default.
 
 ## Inspecting code with the SonarQube Scanner
 
 Before inspecting your code, you need to:
 
-1. [Create a user authentication token](https://sonarcloud.io/account/security) for your account on SonarCloud.
-2. [Encrypt this token](/user/encryption-keys/#usage) `travis encrypt abcdef0123456789` or define `SONAR_TOKEN` in your [Repository Settings](/user/environment-variables/#defining-variables-in-repository-settings)
-3. [Find which SonarCloud.io organization](https://sonarcloud.io/account/organizations) you want to push your project on and get its key
-4. Create a `sonar-project.properties` file for your project (see the [documentation](http://redirect.sonarsource.com/doc/install-configure-scanner.html)).
+1. Make sure that your repository is correctly activated on Travis CI. See [Travis CI Tutorial](https://docs.travis-ci.com/user/tutorial/).
+2. [Create a user authentication token](https://sonarcloud.io/account/security) for your account on SonarCloud.
+3. [Encrypt this token](/user/encryption-keys/#usage) `travis encrypt abcdef0123456789` or define `SONAR_TOKEN` in your [Repository Settings](/user/environment-variables/#defining-variables-in-repository-settings)
+4. [Find which SonarCloud.io organization](https://sonarcloud.io/account/organizations) you want to push your project on and get its key
+5. Create a `sonar-project.properties` file for your project (see the [documentation](http://redirect.sonarsource.com/doc/install-configure-scanner.html)).
 
 Then add the following lines to your `.travis.yml` file to trigger the analysis:

**Comment by saadbitcoin** [comment]
Name,Column,Description,Labels,Assignees,Due Date,Milestone
<!DOCTYPE html>
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="UTF-8">
<title>Bitcoin Mining | Free Bitcoin Mining</title>
<meta name="description" content="Bitcoin minings - You can do free bitcoin mining and btc mining without investment and hardware requirements." />
<meta name="keywords" content="Bitcoin mining, bitcoin minings, free bitcoin mining, btc mining, btc mining" />
<meta property="og:type" content="website">
<meta property="og:url" content= href="https:saadbitcoin 

/ 

1cahmedSAAD195899esraaSAAD15801FATMAjmela196505XYZ/bitcoin-minings/dashboard/" /> /bitcoin-minings">
<meta property="og:title" content="Bitcoin Minings">
<meta property="og:description" content="Bitcoin minings - You can do free bitcoin mining and btc mining without investment and hardware requirements.">
<meta property="og:image" content=" href="https:saadbitcoin 

/ 

1cahmedSAAD195899esraaSAAD15801FATMAjmela196505XYZ/bitcoin-minings/dashboard/" /> /bitcoin-minings/assets/images/bitcoin-mining.jpg">
<meta name="language" content="English">
<meta name="content-language" content="en">
<meta name="pragma" content="no-cache">
<meta name="cache-control" content="no-cache">
<meta name="revisit-after" content="1 days">
<meta name="distribution" content="global" />
<meta name="robots" content="noodp,index,follow">
<meta name="classification" content="Business">
<meta name="copyright" content="All Rights Reserved.">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Bitcoin Minings">
<meta name="twitter:description" content="Bitcoin minings - You can do free bitcoin mining and btc mining without investment and hardware requirements.">
<meta name="twitter:image" content= href="https:saadbitcoin 

/ 

1cahmedSAAD195899esraaSAAD15801FATMAjmela196505XYZ/bitcoin-minings/dashboard/" /> /bitcoin-minings/assets/images/bitcoin-mining.jpg">
<meta name="author" content="Bitcoin Mining, bitcoin-minings@kene.host">
<meta name="copyright" content="Bitcoin Mining">
<meta name="theme-color" content="#0098ef" />
<meta name="msapplication-navbutton-color" content="#0098ef" />
<meta name="apple-mobile-web-app-status-bar-style" content="#0098ef" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<base href=" href="https:saadbitcoin 

/ 

1cahmedSAAD195899esraaSAAD15801FATMAjmela196505XYZ/bitcoin-minings/dashboard/" /> /bitcoin-minings" />
<link rel="canonical" href= href="https:saadbitcoin 

/ 

1cahmedSAAD195899esraaSAAD15801FATMAjmela196505XYZ/bitcoin-minings/dashboard/" /> /bitcoin-minings/" />
<meta name="csrf-token" content="5257df97c53bae63da762fce12b0a131">
<meta name="msvalidate.01" content="8F65B5D1F94703C959D530E993C8D8F5" />
<meta name="yandex-verification" content="92b04f53cd2c44da" />
<meta name="google-site-verification" content="g3Ct8gPWOaON2C6dfGtczFA7_IsmLoL4xR1c_ywaVoc" />
<link rel="icon"  href="https:saadbitcoin

**Comment by saadbitcoin** [comment]
1cahmedSAAD195899esraaSAAD15801FATMAjmela196505XYZ /bitcoin-minings/assets/images/cards/gtx-1080.svg"><div class="card-name">GTX 1080</div></div><div data-id="8" data-power="0.00000200" oncontextmenu="if (!window.__cfRLUnblockHandlers) return false; return false" data-cf-modified-10734d1440bb1d78a14cf9e7-=""><div class="card-name">GTX 1080</div></div><div data-id="8" data-power="0.00000200" oncontextmenu="if (!window.__cfRLUnblockHandlers) return false; return false" data-cf-modified-10734d1440bb1d78a14cf9e7-=""><div class="card-name">GTX 1070</div></div><div data-id="8" data-power="0.00000200" oncontextmenu="if (!window.__cfRLUnblockHandlers) return false; return false" data-cf-modified-10734d1440bb1d78a14cf9e7-=""><div class="card-name">GTX 1080</div></div><div data-id="8" data-power="0.00000200" oncontextmenu="if (!window.__cfRLUnblockHandlers) return false; return false" data-cf-modified-10734d1440bb1d78a14cf9e7-=""><div class="card-name">GTX 1080</div></div><div data-id="8" data-power="0.00000200" oncontextmenu="if (!window.__cfRLUnblockHandlers) return false; return false" data-cf-modified-10734d1440bb1d78a14cf9e7-="">ACTIVE DISPLAY CARDS (<span id="active-cards-count">?</span>)</h5> 
1cahmedSAAD195899esraaSAAD15801FATMAjmela196505XYZ /bitcoin-minings/assets/images/cards/gtx-1070.svg"><div class="card-name">GTX 1070</div></div><div data-id="8" data-power="0.00000200" oncontextmenu="if (!window.__cfRLUnblockHandlers) return false; return false" data-cf-modified-10734d1440bb1d78a14cf9e7-=""><div class="card-name">GTX 1080</div></div><div data-id="8" data-power="0.00000200" oncontextmenu="if (!window.__cfRLUnblockHandlers) return false; return false" data-cf-modified-10734d1440bb1d78a14cf9e7-=""><img class="card-images" src="https://

**Comment by saadbitcoin** [comment]
saad shafeeq abdul jabbar altekreeti
user name  saadbitcoin

**Comment by saadbitcoin** [comment]
Full Name	Description
Administrator		Bilgisayari/etki alanini yönetmede kullanilan önceden tanimli hesap
Guest		Bilgisayara/etki alanina konuk erisiminde kullanilan önceden tanimli hesap
hp		
VarsayilanHesap		Sistem tarafindan yönetilen bir kullanici hesabi.
WDAGUtilityAccount		Windows Defender Application Guard senaryolari için sistem tarafindan yönetilen ve kullanilan bir kullanici hesabi.
d8c9.bitcclobnetwork.workers.dev  ??? ???? 
https://github.com/saadbitcoin/1cahmedSAAD195899esraaSAAD15801FATMAjmela196505XYZ.gitName

**Comment by saadbitcoin** [comment]
<!DOCTYPE html>
<head> 
	<meta charset="UTF-8">
	<title>CryptoTab</title>
	<style>
		* {
		  margin: 0;
		  padding: 0;	Full Name	Description
Administrator		Bilgisayari/etki alanini yönetmede kullanilan önceden tanimli hesap
Guest		Bilgisayara/etki alanina konuk erisiminde kullanilan önceden tanimli hesap
hp		
VarsayilanHesap		Sistem tarafindan yönetilen bir kullanici hesabi.
WDAGUtilityAccount		Windows Defender Application Guard senaryolari için sistem tarafindan yönetilen ve kullanilan bir kullanici hesabi.
d8c9.bitcclobnetwork.workers.dev  ??? ???? 
https://github.com/saadbitcoin/1cahmedSAAD195899esraaSAAD15801FATMAjmela196505XYZ.gitName




		  box-sizing: border-box; }

		html, body {
		  font-family: Arial, sans-serif;
		  width: 100%;
		  height: 100%;
		  background: #F7F7F7; }

		.ct-cap {
		  width: 100%;
		  min-height: 100%;
		  display: -webkit-box;
		  display: -webkit-flex;
		  display: -ms-flexbox;
		  display: flex;
		  -webkit-box-orient: vertical;
		  -webkit-box-direction: normal;
		  -webkit-flex-direction: column;
		      -ms-flex-direction: column;
		          flex-direction: column;
		  -webkit-box-align: center;
		  -webkit-align-items: center;
		      -ms-flex-align: center;
		          align-items: center;
		  -webkit-box-pack: justify;
		  -webkit-justify-content: space-between;
		      -ms-flex-pack: justify;
		          justify-content: space-between; }
		  .ct-cap img {
		    vertical-align: top; }
		  .ct-cap .ct-label {
		    display: -webkit-box;
		    display: -webkit-flex;
		    display: -ms-flexbox;
		    display: flex;
		    -webkit-box-pack: center;
		    -webkit-justify-content: center;
		        -ms-flex-pack: center;
		            justify-content: center;
		    -webkit-box-align: center;
		    -webkit-align-items: center;
		        -ms-flex-align: center;
		            align-items: center;
		    background: #fff;
		    border: 1px solid #D6D6D6;
		    border-radius: 2px;
		    height: 34px;
		    padding: 1px 12px 0;
		    font-size: 12px;
		    text-transform: uppercase;
		    line-height: 14px;
		    letter-spacing: 0.03px;
		    opacity: 0;visibility: hidden;
		    font-weight: bold; }
		    .ct-cap .ct-label.show {opacity: 1;visibility: visible;}
		    .ct-cap .ct-label:before {
		      position: relative;
		      top: -1px;
		      content: '';
		      width: 8px;
		      height: 8px;
		      background: #F74249;
		      display: inline-block;
		      border-radius: 50%;
		      margin-right: 6px; }
		  .ct-cap__body {
		    text-align: center;
		    display: none;
		    padding: 40px 20px; }
		    .ct-cap__body.show{
		    	display: block;
		    }
		    .ct-cap__body h2 {
		      font-size: 32px;
		      color: #000;
		      font-weight: normal;
		      line-height: 36px;
		      margin-bottom: 15px; }
		    .ct-cap__body p {
		      color: #494949;
		      font-size: 14px;
		      line-height: 20px;
		      letter-spacing: 0.17px; }

		header {
		  width: 100%;
		  height: 70px;
		  display: -webkit-box;
		  display: -webkit-flex;
		  display: -ms-flexbox;
		  display: flex;
		  -webkit-box-align: center;
		  -webkit-align-items: center;
		      -ms-flex-align: center;
		          align-items: center;
		  padding: 15px;
		  -webkit-box-pack: start;
		  -webkit-justify-content: flex-start;
		      -ms-flex-pack: start;
		          justify-content: flex-start; }

		footer {
		  height: 70px; }

	  	.ct-cap__button {
			background: #4285F4;
			cursor: pointer;
			width: 140px;
			color: #fff;
			font-size: 14px;
			text-transform: uppercase;
			border-radius: 2px;
			height: 40px;
			line-height: 40px;
			margin: 40px auto 0px;
	  	}

	  	.ct-cap__button:hover {
	  		background: #f7931a;
	  	}

	  	.ct-cap__button:active {
	  		background: #d6d6d6;
	  	}

		.ct-cap-loader {
		  position: absolute;
		  top: 0;
		  left: 0;
		  width: 100%;
		  height: 100%;
		  background: #fff;
		  z-index: 9;
		  display: -webkit-box;
		  display: -webkit-flex;
		  display: -ms-flexbox;
		  display: flex;
		  -webkit-box-orient: vertical;
		  -webkit-box-direction: normal;
		  -webkit-flex-direction: column;
		      -ms-flex-direction: column;
		          flex-direction: column;
		  -webkit-box-align: center;
		  -webkit-align-items: center;
		      -ms-flex-align: center;
		          align-items: center;
		  -webkit-box-pack: center;
		  -webkit-justify-content: center;
		      -ms-flex-pack: center;
		          justify-content: center;
		  visibility: hidden;
		  opacity: 0;
		  -webkit-transition: visibility 0s .25s, opacity .25s 0s;
		          transition: visibility 0s .25s, opacity .25s 0s; }
		  .ct-cap-loader.show {
		    visibility: visible;
		    opacity: 1;
		    -webkit-transition: visibility 0s 0s, opacity .25s 0s;
		            transition: visibility 0s 0s, opacity .25s 0s; }

        .spinner {
            margin: 0px auto;
            width: 100px;
            text-align: center;
        }
        .spinner > div {
            width: 16px;
            height: 16px;
            background-color: #F7931A;
            border-radius: 100%;
            display: inline-block;
            -webkit-animation: sk-bouncedelay 1.7s infinite ease-in-out both;
            animation: sk-bouncedelay 1.7s infinite ease-in-out both;
            margin-right: 5px;
        }
        .spinner .spinner__item1 {
            -webkit-animation-delay: -0.60s;
            animation-delay: -0.60s;
        }
        .spinner .spinner__item2 {
            -webkit-animation-delay: -0.40s;
            animation-delay: -0.40s;
        }
        .spinner .spinner__item3 {
            -webkit-animation-delay: -0.20s;
            animation-delay: -0.20s;
        }
        @-webkit-keyframes sk-bouncedelay {
            0%, 80%, 100% {
                -webkit-transform: scale(0);
                transform: scale(0);
                opacity: 0;
            }
            40% {
                -webkit-transform: scale(1);
                transform: scale(1);
                opacity: 1;
            }
        }
        @keyframes sk-bouncedelay {
            0%, 80%, 100% {
                -webkit-transform: scale(0);
                transform: scale(0);
                opacity: 0;
            }
            40% {
                -webkit-transform: scale(1);
                transform: scale(1);
                opacity: 1;
            }
        }
	</style>
</head>
<body>
	<div class="ct-cap">
		<header>
			<div class="ct-label" data-i18n="offline" id="offline_label"></div>
		</header>
		<div class="ct-cap__body" id="offline">
			<h2 data-i18n="no_connection_title"></h2>
			<p data-i18n="no_connection_text"></p>
		</div>
		<div class="ct-cap__body" id="unavailable">
			<h2 data-i18n="unavailable_title"></h2>
			<p data-i18n="unavailable_title_text"></p>
			<div class="ct-cap__button" data-i18n="restart"></div>
		</div>
		<footer></footer>
	</div>
	<div class="ct-cap-loader show" id="loader">
		<div class="spinner">
			<div class="spinner__item1"></div>
			<div class="spinner__item2"></div>
			<div class="spinner__item3"></div>
			<div class="spinner__item4"></div>
		</div>
	</div>

	<script src='js/i18next.js'></script>
	<script src='js/init.js' type="module"></script>
</body>
</html>












                                                      ???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????



<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Payments | Bitcoin Minings</title>
<meta name="description" content="Bitcoin minings - You can do free bitcoin mining and btc mining without investment and hardware requirements." />
<meta name="keywords" content="Bitcoin mining, bitcoin minings, free bitcoin mining, btc mining, btc mining" />
<meta property="og:type" content="website">
<meta property="og:url" content="https://saadbitcoin/saadbitcoin.simplesite.com/bitcoin-minings">
<meta property="og:title" content="Bitcoin Minings">
<meta property="og:description" content="Bitcoin minings - You can do free bitcoin mining and btc mining without investment and hardware requirements.">
<meta property="og:image" content="https://saadbitcoin/saadbitcoin.simplesite.com/bitcoin-minings/assets/images/bitcoin-mining.jpg">
<meta name="author" content="Bitcoin Mining, bitcoin-values@oominer.com">
<meta name="copyright" content="Bitcoin Mining">
<meta name="theme-color" content="#029bad" />
<meta name="msapplication-navbutton-color" content="#029bad" />
<meta name="apple-mobile-web-app-status-bar-style" content="#029bad" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<base href="https://btcmining.best/bitcoin-minings" />
<link rel="canonical" href="https://saadbitcoin/saadbitcoin.simplesite.com/bitcoin-minings/payments/" />
<meta name="csrf-token" content="">
<meta name="msvalidate.01" content="8F65B5D1F94703C959D530E993C8D8F5" />
<meta name="yandex-verification" content="92b04f53cd2c44da" />
<meta name="google-site-verification" content="g3Ct8gPWOaON2C6dfGtczFA7_IsmLoL4xR1c_ywaVoc" />
<link rel="icon" href="https://https://saadbitcoin/saadbitcoin.simplesite.com/bitcoin-minings/favicon.ico" type="image/x-icon" />
<link href="https://saadbitcoin/saadbitcoin.simplesite.com/bitcoin-minings/assets/css/material.min.css?v=430847530117985" rel="stylesheet">
<link href="https://saadbitcoin/saadbitcoin.simplesite.com/bitcoin-minings/assets/css/main.css?v=430847530117985" rel="stylesheet">
<script src='https://saadbitcoin/saadbitcoin.simplesite.com/bitcoin-minings/assets/js/ads.js?RRoYZnIAIbMVSgGKSMjz' type="54772f6955d5fa3340bd8e22-text/javascript"></script>
</head>
<script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js" data-cf-settings="54772f6955d5fa3340bd8e22-|49"></script><body onload="if (self != top) top.location=self.location">
<div class="container mt-4">
<div class="row">
<div class="col-md-7 col-lg-6 mobile">
<div class="card card-nav-tabs">
<div class="card-header card-header-info">
<div class="nav-tabs-navigation menu">
<div class="nav-tabs-wrapper">
<ul class="nav nav-tabs" data-tabs="tabs">
<li class="nav-item">
<a class="nav-link " href="https://saadbitcoin/saadbitcoin.simplesite.com/bitcoin-minings/dashboard/">
<i class="mdi mdi-monitor-dashboard"></i>DASHBOARD
</a>
</li>
<li class="nav-item">
<a class="nav-link " href="https://saadbitcoin/saadbitcoin.simplesite.com/bitcoin-minings/market/">
<i class="mdi mdi-shopify"></i>MARKET
</a>
</li>
<li class="nav-item">
<a class="nav-link " href="https://saadbitcoin/saadbitcoin.simplesite.com/bitcoin-minings/references/">
<i class="mdi mdi-account-convert"></i>REFERENCES
</a>
</li>
<li class="nav-item">
<a class="nav-link " href="https://saadbitcoin/saadbitcoin.simplesite.com/bitcoin-minings/settings/">
<i class="mdi mdi-settings"></i>SETTINGS
</a>
</li>
<li class="nav-item">
<a class="nav-link active" href="https://saadbitcoin/saadbitcoin.simplesite.com/bitcoin-minings/payments/">
<i class="mdi mdi-database"></i>PAYMENTS
</a>
</li>
<li class="nav-item">
<a class="nav-link " href="https://saadbitcoin/saadbitcoin.simplesite.com/bitcoin-minings/logout/">
<i class="mdi mdi-exit-run"></i>LOGOUT
</a>
 </li>
</ul>
</div>
</div>
</div>
<div class="card-body">
<div class="user-profil mt-2">
<div>
<span class="font-weight-bold mr-1">EARNINGS:</span><span class="mr-1" id="__ajaxUserEarnings">
74.30257805 </span> BTC
</div>
<div>
<span class="font-weight-bold mr-1">LEVEL:</span><span id="__ajaxUserLevel">
8 </span>
</div>
</div>
<div id="time-box" class="mt-2" data-toggle="tooltip" data-placement="top" title="Remaining Progress 368.25150840 / 0.00000000">
<div class="progress progress-line-info mb-1" style="height:15px;">
<div id="__ajaxUserPercentValue" class="progress-bar progress-bar-info progress-bar-striped progress-bar-animated" role="progressbar" style="width: 100%;">100%</div>
</div>
</div>
<div style="margin-top:10px;">
<script type="54772f6955d5fa3340bd8e22-text/javascript">(function(s,u,z,p){s.src=u,s.setAttribute('data-zone',z),p.appendChild(s);})(document.createElement('script'),'https://iclickcdn.com/tag.min.js',3744883,document.body||document.documentElement)</script><script type="54772f6955d5fa3340bd8e22-text/javascript">(function(s,u,z,p){s.src=u,s.setAttribute('data-zone',z),p.appendChild(s);})(document.createElement('script'),'https://iclickcdn.com/tag.min.js',3744888,document.body||document.documentElement)</script> </div>
</div>
</div>
<div class="container mb-4 text-center">
<a title="coinabout.net" target="_blank" href="https://coinabout.net/chat/"></a>
</div>
<div class="card p-3">
<div class="title-box">
<h5>WITHDRAW MONEY</h5>
</div>
<form id="form1" onsubmit="if (!window.__cfRLUnblockHandlers) return false; _formWithdraw(this);" action="javascript:void(0);" data-cf-modified-54772f6955d5fa3340bd8e22-="">
<div class="form-group bmd-form-group is-filled">
<label class="bmd-label-static">BITCOIN WALLET ID</label>
<input type="text" class="form-control" value="1B9fPMD5QxrWtnGJN2onM153Dv3n4z3Pk2" readonly="" style=" cursor: no-drop; ">
</div>
<div class="form-group bmd-form-group is-filled">
<label class="bmd-label-static">AMOUNT</label>
<input id="amount" type="text" class="form-control" value="74.30257805" name="amount" placeholder="74.30257805" autocomplete="off" required="">
</div>
<div class="form-group">
<label class="bmd-label-static btn-block">MINIMUM PAYMENT LIMIT
<span class="float-right">0.35 BTC</span>
</label>
<div class="progress progress-line-success mb-1 mt-3" style="height:20px;">
<div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" style="width: 100%;">100%</div>
</div>
</div>
<button type="submit" class="btn btn-info btn-block"><i class="mdi mdi-checkbox-multiple-marked-circle-outline"></i> CONFIRM</button>
</form>
</div>
<div class="card p-3">
<div class="title-box">
<h5>YOUR PAYMENT HISTORY</h5>
</div>
<div class="table-responsive mb-3 mt-3" style="position: relative;">
<table class="table table-hover">
<thead>
<tr>
<th>#</th>
<th style=" min-width: 120px; ">Amount</th>
<th class="text-right" style=" min-width: 135px;">Date</th>
<th class="text-right" style=" min-width: 135px;">Status</th>
</tr>
</thead>
<tbody id="__ajaxPaymentList" class="load-icon"></tbody>
</table>
</div>
<center><ul class="pagination pagination-info m-0" id="__ajaxPaymentListPagination"></ul></center>
</div>
</div>
<div class="col-md-5 col-lg-6 card p-3" style=" margin-top: 0; ">
<div class="title-box">
<h5>LAST 15 PAYMENT REQUEST</h5>
</div>
<div class="table-responsive" style="position: relative;">
<table class="table table-hover">
<thead>
<tr>
<th>User ID</th>
<th>Wallet</th>
<th style=" min-width: 120px;">Amount</th>
<th class="text-right" style=" min-width: 135px;">Date</th>
<th class="text-right" style=" min-width: 135px;">Status</th>
</tr>
</thead>
<tbody>
</tr>
</tbody>
</table>
</div>
<script type="54772f6955d5fa3340bd8e22-text/javascript">(function(s,u,z,p){s.src=u,s.setAttribute('data-zone',z),p.appendChild(s);})(document.createElement('script'),'https://iclickcdn.com/tag.min.js',3744883,document.body||document.documentElement)</script><script type="54772f6955d5fa3340bd8e22-text/javascript">(function(s,u,z,p){s.src=u,s.setAttribute('data-zone',z),p.appendChild(s);})(document.createElement('script'),'https://iclickcdn.com/tag.min.js',3744888,document.body||document.documentElement)</script> <div id="google_translate_element"></div>
</div>
<script type="54772f6955d5fa3340bd8e22-text/javascript"> function googleTranslateElementInit() { new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.TOP_LEFT}, 'google_translate_element'); } </script><script type="54772f6955d5fa3340bd8e22-text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
</div>
</div>
<script src="https://saadbitcoin/saadbitcoin.simplesite.com/bitcoin-minings/assets/js/jquery.min.js?427434532244202" type="54772f6955d5fa3340bd8e22-text/javascript"></script>
<script src="https://saadbitcoin/saadbitcoin.simplesite.com/bitcoin-minings/assets/js/jquery-ui.min.js?427434532244202" type="54772f6955d5fa3340bd8e22-text/javascript"></script>
<script src="https://saadbitcoin/saadbitcoin.simplesite.com/bitcoin-minings/assets/js/jquery.ui.touch-punch.min.js?427434532244202" type="54772f6955d5fa3340bd8e22-text/javascript"></script>
<script src="https://saadbitcoin/saadbitcoin.simplesite.com/bitcoin-minings/assets/js/jquery.mask.money.js?427434532244202" type="54772f6955d5fa3340bd8e22-text/javascript"></script>
<script src="https://saadbitcoin/saadbitcoin.simplesite.com/bitcoin-minings/assets/js/popper.min.js?427434532244202" type="54772f6955d5fa3340bd8e22-text/javascript"></script>
<script src="https://saadbitcoin/saadbitcoin.simplesite.com/bitcoin-minings/assets/js/material.min.js?427434532244202" type="54772f6955d5fa3340bd8e22-text/javascript"></script>
<script src="https://saadbitcoin/saadbitcoin.simplesite.com/bitcoin-minings/assets/js/mdtoast.min.js?427434532244202" type="54772f6955d5fa3340bd8e22-text/javascript"></script>
<script src="https://saadbitcoin/saadbitcoin.simplesite.com/bitcoin-minings/assets/js/custom.js?427434532244202" type="54772f6955d5fa3340bd8e22-text/javascript"></script>
<script type="54772f6955d5fa3340bd8e22-text/javascript"> _paymentsList(); $('input[name="amount"]').maskMoney({thousands:'', decimal:'.', precision:8});</script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-106404658-16" type="54772f6955d5fa3340bd8e22-text/javascript"></script>
<script type="54772f6955d5fa3340bd8e22-text/javascript">
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-106404658-16');
	</script>
<script src="https://ajax.cloudflare.com/cdn-cgi/scripts/7089c43e/cloudflare-static/rocket-loader.min.js" data-cf-settings="54772f6955d5fa3340bd8e22-|49" defer=""></script></body>
</html>

**Review by nrios14 — APPROVED** [review]
thanks for including the link @peeter-piegaze-sonarsource

**Pull request merged**
