### PR TITLE
Generate table for on-demand Python runtimes

### PR DESCRIPTION
**Pull request by BanzaiMan**
This PR dynamically generates the list of Python archives available for on-demand installation.

It does so by fetching the list of archives available on S3, dumping the list into a YAML file, and reading it to generate the table. The table looks a little ugly as a source; I could not figure out a cleaner way to do that with `rowspan`.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Note that, with this PR, we are deploying the app to https://docs-staging.travis-ci.com/ from the `staging` branch.

In particular, you can see how the table looks at https://docs-staging.travis-ci.com/user/languages/python/#python-runtime-list.

**Comment by plaindocs** [comment]
I'm way more than :100: excited about generating lists of version numbers, but holy *hell* that is an ugly table.

I'm not even sure we *need* a table, how about something like:

And we can format the lists into 3 columns like in https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Even-more-Nodejs-versions

## Trusty

### Python

python-2.6.9
python-2.6
python-2.7.10
python-2.7.11
python-2.7.12
python-2.7.13
python-2.7.13rc1
python-2.7.3
python-2.7.6
python-2.7.9
python-2.7
python-3.2.6
python-3.2
python-3.3.3
python-3.3.5
python-3.3.6
python-3.3
python-3.4.2
python-3.4.3
python-3.4.4
python-3.4.5
python-3.4.6
python-3.4
python-3.5-dev
python-3.5.0
python-3.5.0rc2
python-3.5.0rc4
python-3.5.1
python-3.5.2
python-3.5.3
python-3.5
python-3.6-dev
python-3.6.0
python-3.6.0a2
python-3.6.0a4
python-3.6.0b1
python-3.6.0b2
python-3.6.0b3
python-3.6.0rc1
python-3.6.0rc2
python-3.6.1
python-3.6
python-3.7-dev

### PyPi

pypy-2.6.1
pypy-4.0.1
pypy-4.0
pypy-5.0.0
pypy-5.0.1
pypy-5.1.1
pypy-5.1
pypy-5.3.1
pypy-5.3
pypy-5.4.1
pypy-5.4
pypy-5.6.0
pypy-5.6
pypy-5.7.1
pypy-5.7
pypy
pypy3-2.4.0
pypy3-2.4
pypy3.3-5.2-alpha1
pypy3.3-5.5-alpha
pypy3.5-5.7.1-beta
pypy3.5
pypy3

## Precise

**Comment by plaindocs** [comment]
LMK if that looks good and I'll rustle up a PR against your branch

**Comment by plaindocs** [comment]
Looks like this is erroring because:

```
Aws::Errors::MissingRegionError: missing region; use :region option or export region name to ENV['AWS_REGION']
```

**Pull request closed without merging**
