### PR TITLE
minor updates on the snap deploy

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by elopio** [comment]
We are now calling it Snaps Store, and we are trying to phase out the linked tutorial in favour of more up-to-date documentations, so I would appreciate if you help us landing this changes. Thanks :)

**Comment by plaindocs** [comment]
Thanks for the speedy update!

**Comment by elopio** [comment]
Thanks to you @plaindocs! We want to make a proper deployment provider, so let me introduce you to my friend @kyrofa, who will be working on that. Hopefully these docs will be nicer soon :)

**Comment by plaindocs** [comment]
That is awesome news :-)

**Pull request merged**
