### PR TITLE
Remove Divshot

### PR DESCRIPTION
**Pull request by acorncom**
They merged with Firebase last fall (Nov 2015 if I remember correctly)

### CODE REVIEW

**Comment by plaindocs** [comment]
Ah, thanks for the heads up. Do you mind removing Divshot from the list of Deploments in `_data/deployments.yml ` as well?

**Comment by acorncom** [comment]
Done

**Comment by plaindocs** [comment]
I think I'm missing something - I see only the one file affected still.

**Comment by acorncom** [comment]
No, I was missing something.  It's called trying to move too fast.  Sorry :-)

**Comment by plaindocs** [comment]
Thanks again!

**Pull request merged**
