### PR TITLE
Remove worker pages and improve Environment reference

### PR DESCRIPTION
**Pull request by plaindocs**
WIP do not merge. Comments welcome.

### CODE REVIEW

**Comment by plaindocs** [comment]
@MariadeAnton I can break this into two phases if you want to merge the workers stuff before I start looking too deeply into the improving the environment reference.

**Comment by MariadeAnton** [comment]
Sorry for the delay, @plaindocs - I thought I had left some thoughts here already but I'm afraid I didn't

I think it looks good so far, which of the details in those worker pages were you planning on keeping? I'm thinking some of the file-system stuff might be useful in the environment reference.

**Comment by plaindocs** [comment]
Yeah, all of the file system stuff is already in the table in `ci-environment.md` - so I added the info to the OS-X page. So still needs work, but I think good to delete for now.

**Comment by MariadeAnton** [comment]
Thank you for clarifying. 🚢 'ing 🇮🇹

**Pull request merged**
