### PR TITLE
Add notes about APT source requests are not currently processed

### PR DESCRIPTION
**Pull request by BanzaiMan**

### CODE REVIEW

**Comment by BanzaiMan** [comment]
travis-build needs to change the message, and apt-source-whitelist README needs to be updated.

**Comment by plaindocs** [comment]
@BanzaiMan I think this is no longer relevant, is that correct?

**Comment by BanzaiMan** [comment]
@plaindocs It still is, but needs update.

**Comment by remram44** [comment]
The fact that the whitelist process is stuck by lack of manpower to review PRs should be listed clearly IMHO. It is not tragic, there are sometimes workarounds, but users should know not to hold their breath over this.

**Pull request merged**
