### PR TITLE
Prefer to use atoum through Composer

### PR DESCRIPTION
**Pull request by Hywan**
atoum PHAR is no longer the best way to use it. This is better to grab it through Composer instead.

### CODE REVIEW

**Comment by plaindocs** [comment]
Thanks!

**Comment by Hywan** [comment]
@plaindocs Thank **you** 😃. Do you have an idea when the documentation will be updated?

**Comment by plaindocs** [comment]
Just takes a couple of minutes to propagate.

**Comment by Hywan** [comment]
Thanks :+1:.

**Pull request merged**
