### PR TITLE
Add Bionic PHP extention section

### PR DESCRIPTION
**Pull request by mustafa-travisci**
Please review. Thanks.

### CODE REVIEW

**Comment by Geolim4** [comment]
Cool, thanks @mustafa-travisci :)

**Comment by LadyMiss88** [comment]
can i change https://www.applecrumbyandfish.com/product/19710/applecrumbytm-chlorine-free-premium-overnight-baby-pull-up-diapers-xxl15-four-pack-with-free-applecrumbytm-premium-pure-water-wipes-3-pack-bundle-50-sheets-xylitol-for-oral-care.html

**Review by cesar-cs — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
