### PR TITLE
Update documentation to reflect the removal of only_create_app_version option in dplv2

### PR DESCRIPTION
**Pull request by neilhut42**
Changed to replect removal of --only_create_app_version option.  (https://github.com/travis-ci/dpl/commit/bac0e9a4e8a200ef6f1ab95362e7d53a092f28fc)

### CODE REVIEW

**Comment by Montana** [comment]
The option, `only_create_app_version` would be true for AWS Elastic Beanstalk.

**Comment by neilhut42** [comment]
> The option, `only_create_app_version` would be true for AWS Elastic Beanstalk.

Actually, it's not.  This has been removed (and broke our deploys as a result).  Please see the commit in question. 

Simplify "upload without deploy" workflow
Remove --only_create_app_version and mark --env as optional. If --env is
unset, only upload the app version without deploying it to a new
environment.

https://github.com/travis-ci/dpl/commit/bac0e9a4e8a200ef6f1ab95362e7d53a092f28fc

**Comment by SolarUltima** [comment]
Thanks @Montana, 

Our setup had a similar issue and this is good advice.

**Comment by neilhut42** [comment]
> Thanks @Montana,
> 
> Our setup had a similar issue and this is good advice.

Unless you use dplv2 (edge: true) - then using the option will cause an error " Unknown option: --only_create_app_version" during the build.

**Comment by michal-at-travisci** [comment]
@Montana can this one be merged as valid?

**Comment by nrios14** [comment]
> @Montana can this one be merged as valid?

Found this older PR, still open. Can I merge it @Montana ?

**Comment by Montana** [comment]
This is still valid @michal-at-travisci & @nrios14

**Review by Montana — APPROVED** [review]
Hard to repro, but still repro'd - I approved.

**Pull request merged**
