### PR TITLE
Update r.md

### PR DESCRIPTION
**Pull request by markgene**
The field "language: r" seems case sensitive. I used lower cases as in the doc but it failed until I changed it to upper cases.

### CODE REVIEW

**Comment by BanzaiMan** [comment]
Hi, there.

Could you show how you came to this conclusion?

I ran a quick test to confirm that this is not the case. See https://travis-ci.org/BanzaiMan/travis_production_test/builds/377412968 and its configuration https://github.com/BanzaiMan/travis_production_test/blob/9d73432156304c6fafb2c15e83354af5ec5dcaa0/.travis.yml.

The `language` values should be normalized to lower case when we process them.

**Comment by markgene** [comment]
Hi there, thank you for your response. I added .travis.yml file to my GitHub repo (the content of .travis.yml is shown below). But, the Travis CI gives me the page with some message like "Read our docs". I changed `language: r` to `language: R` because I have another repo which ran successfully with `R` in upper case. Then, it works.

```
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
```

**Comment by BanzaiMan** [comment]
Do you have a build log URL with `language: r` and doesn't work?

**Comment by BanzaiMan** [comment]
Please try again with `language: r`. Your build request for https://github.com/markgene/mutils/commit/fa63014 was rejected (https://travis-ci.org/markgene/mutils/requests) because `.travis.yml` was invalid, not because the `language` value was lower case.

**Comment by plaindocs** [comment]
I'm closing this for now. Please reopen if you still think it is an issue.

**Pull request closed without merging**
