### PR TITLE
Add JWT deprecation warning and .warning class

### PR DESCRIPTION
**Pull request by BanzaiMan**
jwt_addon_-_travis_ci

### CODE REVIEW

**Comment by plaindocs** [comment]
Can we tone down the red slightly?

**Comment by BanzaiMan** [comment]
The only other red we have defined is `$red-light`, which gives us

jwt_addon_-_travis_ci

We can choose another color, but I'd rather not.

**Comment by plaindocs** [comment]
I'm ok with `red-light` if you are, and I definitely prefer it to `brick-red`

**Comment by BanzaiMan** [comment]
Very well!

**Comment by plaindocs** [comment]
Danke! <3

**Pull request merged**
