### PR TITLE
Update javascript-with-nodejs.md

### PR DESCRIPTION
**Pull request by cyberhck**

### CODE REVIEW

**Comment by cyberhck** [comment]
gonna get merged quite soon?

**Comment by BanzaiMan** [comment]
I'll repost my comment to the duplicate issue https://github.com/travis-ci/docs-travis-ci-com/pull/1325#issuecomment-316160958

----

I think this section needs a different approach. Enumerating latest versions and keeping the list up-to-date is cumbersome.

Instead, we should simply point out that Node.js versions can be specified by the `node_js` key, and that the list can be obtained by `nvm ls-remote`. We could also generate the list of Node.js versions in https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Even-more-Nodejs-versions as well.

**Comment by cyberhck** [comment]
How are you picturing the text to look like? Remove the current versions and mentioning:
"Any nodejs version can be selected with node_js key. List of nodejs versions can be obtained `nvm ls-remote`?"
About that link, How do we do that? On travis? Once we build, we generate it and commit? Need a little more info.

Thanks :slightly_smiling_face:

**Comment by plaindocs** [comment]
As well as @BanzaiMan s comments above, we're moving all version info to the environment reference and the work in https://github.com/travis-ci/docs-travis-ci-com/pull/1388 means we can close this I think.

Thanks @cyberhck ! If you'd like to make a PR against that branch mentioning `nvm ls-remote` I'd be happy to merge it.

**Comment by cyberhck** [comment]
@plaindocs I'll do that next time I'm on travis, right now I'm very busy at work.

**Pull request closed without merging**
