### PR TITLE
node.js javascript: Add details on using io.js builds

### PR DESCRIPTION
**Pull request by paulirish**
… along with more detail on NVM as the version manager, here.

ref:
http://docs.travis-ci.com/user/build-environment-updates/2015-02-03/#iojs_support

### CODE REVIEW

**Comment by ljharb** [comment]
Awesome!

It'd be cool to also add "stable", "unstable", and "node" (which is "stable") aliases to the docs :-)

**Comment by paulirish** [comment]
@ljharb done

**Comment by ljharb** [comment]
👍 LGTM!

**Comment by BanzaiMan** [comment]
Sorry for letting this languish. Could you resolve the recent conflicts? (I'm really sorry!)

**Comment by paulirish** [comment]
conflicts resolved.

**Pull request merged**
