### PR TITLE
Playing catch up with the deployment docs

### PR DESCRIPTION
**Pull request by plaindocs**
Fixing all the missing deployment targets listed in #888 one by one. WIP

### CODE REVIEW

**Comment by lislis** [comment]
@plaindocs I added some pacing to the list. But somehow I think that's not actually what you wanted?
Looks like this:
screen shot 2017-01-25 at 14 25 13

**Comment by plaindocs** [comment]
THANKS @lislis - it wasn't but it was also necessary! :-)

I was talking about the list numbering. Could we change the sublist to `a b c` or `i ii iii` not `1 2 3`. Kinda like here https://github.com/travis-ci/dpl/#catalyze

**Comment by lislis** [comment]
@plaindocs here you go

screen shot 2017-01-25 at 16 22 43

**Comment by plaindocs** [comment]
Just waiting on some Transifex info - but this can be reviewed and merged and I'll add that later.

**Comment by plaindocs** [comment]
@MariadeAnton I'm gonna go ahead and merge this because of all the missing links, please give it a once over if you find the time anyway.

**Pull request merged**
